source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CDAL_Example' do
  inherit! :search_paths
  pod 'CDAL', :path => '../'
end

target 'CDAL_Tests' do
  inherit! :search_paths
  pod 'CDAL', :path => '../'

  pod 'Quick', '~> 0.10.0'
  pod 'Nimble', '~> 5.0.0'
end
